const PDFDocument = require('pdfkit');
const time = require('../utils/time');
const { BRAND_COLOR } = require('./mailService');

/*
 * PDF progress report of a student (phase 2 contract section 3.3): A4, CampusLink header, student, group,
 * academic year, attendance and grades tables, generated date, in French ("tu" is not needed: the report is
 * written in the third person) or English. Built with pdfkit and its standard Helvetica fonts (WinAnsi
 * encoding: every French accented letter is supported; other characters are approximated, see pdfText).
 */

const BRAND = BRAND_COLOR || '#253C6D';
const TEXT_COLOR = '#1F2937';
const MUTED_COLOR = '#5B6475';
const BORDER_COLOR = '#D5DAE3';
const HEADER_FILL = '#E8ECF4';
const LEVEL_COLORS = { OK: '#2E7D32', WARNING: '#8A5300', CRITICAL: '#B3261E' };
const MARGIN = 50;
const FOOTER_SPACE = 40;
const ROW_HEIGHT = 20;

const TEXTS = {
  fr: {
    documentTitle: 'Relevé de suivi',
    subtitle: 'Relevé de suivi : assiduité et notes',
    student: 'Étudiant(e)',
    email: 'E-mail',
    group: 'Groupe',
    noGroup: 'Aucun groupe',
    academicYear: 'Année universitaire',
    generatedOn: 'Généré le',
    kpiAbsence: "Taux d'absence global",
    kpiAverage: 'Moyenne générale',
    kpiAbsentHours: "Heures d'absence",
    attendance: 'Assiduité',
    attendanceNote: (warning, critical) =>
      `Taux d'absence = heures d'absence non justifiées / heures de cours tenues. Seuils : avertissement ${warning}, alerte ${critical}.`,
    subject: 'Matière',
    heldHours: 'Heures tenues',
    absentHours: "Heures d'absence",
    rate: "Taux d'absence",
    level: 'Niveau',
    levels: { OK: 'Normal', WARNING: 'Avertissement', CRITICAL: 'Alerte' },
    noAttendance: "Aucune séance terminée pour l'instant.",
    grades: 'Notes',
    gradesNote: 'Moyennes sur 20, pondérées par les coefficients des évaluations publiées.',
    assessments: 'Évaluations notées',
    average: 'Moyenne /20',
    overallAverage: 'Moyenne générale pondérée',
    noGrades: "Aucune note publiée pour l'instant.",
    details: 'Détail des évaluations',
    date: 'Date',
    assessment: 'Évaluation',
    coefficient: 'Coef.',
    score: 'Note',
    notGraded: 'Non noté',
    hoursUnit: 'h',
    colon: '\u00a0: ',
    footer: 'Document généré par CampusLink',
    page: (current, total) => `Page ${current} / ${total}`,
    filePrefix: 'releve-campuslink',
  },
  en: {
    documentTitle: 'Progress report',
    subtitle: 'Progress report: attendance and grades',
    student: 'Student',
    email: 'Email',
    group: 'Group',
    noGroup: 'No group',
    academicYear: 'Academic year',
    generatedOn: 'Generated on',
    kpiAbsence: 'Overall absence rate',
    kpiAverage: 'Overall average',
    kpiAbsentHours: 'Absent hours',
    attendance: 'Attendance',
    attendanceNote: (warning, critical) =>
      `Absence rate = unexcused absent hours / hours of classes held. Thresholds: warning ${warning}, alert ${critical}.`,
    subject: 'Subject',
    heldHours: 'Hours held',
    absentHours: 'Absent hours',
    rate: 'Absence rate',
    level: 'Level',
    levels: { OK: 'Normal', WARNING: 'Warning', CRITICAL: 'Alert' },
    noAttendance: 'No class has been held yet.',
    grades: 'Grades',
    gradesNote: 'Averages out of 20, weighted by the coefficients of the published assessments.',
    assessments: 'Graded assessments',
    average: 'Average /20',
    overallAverage: 'Overall weighted average',
    noGrades: 'No published grade yet.',
    details: 'Assessment details',
    date: 'Date',
    assessment: 'Assessment',
    coefficient: 'Coef.',
    score: 'Score',
    notGraded: 'Not graded',
    hoursUnit: 'h',
    colon: ': ',
    footer: 'Generated by CampusLink',
    page: (current, total) => `Page ${current} of ${total}`,
    filePrefix: 'campuslink-report',
  },
};

// ---------- Text helpers ----------

// Characters of the WinAnsi encoding outside Latin-1 (the standard PDF fonts use WinAnsi).
const WIN_ANSI_EXTRA = new Set('€‚ƒ„…†‡ˆ‰Š‹ŒŽ‘’“”•–—˜™š›œžŸ');
const isWinAnsi = (char) => {
  const code = char.codePointAt(0);
  return (code >= 0x20 && code <= 0x7e) || (code >= 0xa0 && code <= 0xff) || WIN_ANSI_EXTRA.has(char);
};

/**
 * Text the standard PDF fonts can draw: every French letter is kept as is (é, è, à, ç, œ, ï...); thin and
 * narrow spaces become no-break spaces; other letters lose their accents when that is enough (ő → o), else
 * become "?". Line breaks and tabs become spaces.
 */
const pdfText = (value) => {
  const text = String(value ?? '')
    .replace(/[\u2007\u2009\u202f]/g, '\u00a0')
    .replace(/[\r\n\t]+/g, ' ');
  let result = '';
  for (const char of text) {
    if (isWinAnsi(char)) {
      result += char;
      continue;
    }
    const stripped = char.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    result += stripped && [...stripped].every(isWinAnsi) ? stripped : '?';
  }
  return result;
};

const numberFormatters = new Map();
const formatNumber = (value, locale, { min = 0, max = 2, style = 'decimal' } = {}) => {
  const key = `${locale}|${min}|${max}|${style}`;
  if (!numberFormatters.has(key)) {
    numberFormatters.set(
      key,
      new Intl.NumberFormat(locale === 'en' ? 'en-US' : 'fr-FR', {
        style,
        minimumFractionDigits: min,
        maximumFractionDigits: max,
      })
    );
  }
  return numberFormatters.get(key).format(value);
};
const formatPercent = (rate, locale) => formatNumber(rate, locale, { max: 1, style: 'percent' });
const formatHours = (hours, locale, texts) => `${formatNumber(hours, locale, { max: 2 })} ${texts.hoursUnit}`;
const formatAverage = (average, locale) => (average === null || average === undefined ? '—' : formatNumber(average, locale, { min: 2, max: 2 }));

const formatDateTime = (date, locale) =>
  new Intl.DateTimeFormat(locale === 'en' ? 'en-US' : 'fr-FR', {
    dateStyle: 'long',
    timeStyle: 'short',
    hourCycle: 'h23',
    timeZone: time.getAppTimezone(),
  }).format(date);
const formatDate = (date, locale) =>
  new Intl.DateTimeFormat(locale === 'en' ? 'en-US' : 'fr-FR', { dateStyle: 'medium', timeZone: time.getAppTimezone() }).format(
    new Date(date)
  );

const slug = (value) =>
  String(value ?? '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter(Boolean)
    .join('-');

// Download name, e.g. "releve-campuslink-haddad-yasmine-2026-10-08.pdf".
const reportFilename = (student, locale, now = new Date()) => {
  const texts = TEXTS[locale === 'en' ? 'en' : 'fr'];
  const name = [slug(student?.lastname), slug(student?.firstname)].filter(Boolean).join('-') || 'student';
  return `${texts.filePrefix}-${name}-${time.formatLocalDate(now)}.pdf`;
};

// ---------- Drawing ----------

// Truncates `text` with an ellipsis so it fits in `width` at the current font and size.
const fit = (doc, value, width) => {
  const text = pdfText(value);
  if (doc.widthOfString(text) <= width) return text;
  let result = text;
  while (result.length > 1 && doc.widthOfString(`${result}…`) > width) result = result.slice(0, -1);
  return `${result.trimEnd()}…`;
};

const createWriter = (doc) => {
  const pageWidth = doc.page.width;
  const contentWidth = pageWidth - MARGIN * 2;
  const bottom = () => doc.page.height - MARGIN - FOOTER_SPACE;
  let y = MARGIN;

  const writer = {
    contentWidth,
    get y() {
      return y;
    },
    set y(value) {
      y = value;
    },
    // Starts a new page when `height` does not fit; returns true when it did.
    ensure(height) {
      if (y + height <= bottom()) return false;
      doc.addPage();
      y = MARGIN;
      return true;
    },
    sectionTitle(title) {
      writer.ensure(60);
      y += 14;
      doc.font('Helvetica-Bold').fontSize(14).fillColor(BRAND).text(pdfText(title), MARGIN, y, { lineBreak: false });
      y += 20;
      doc.moveTo(MARGIN, y).lineTo(MARGIN + contentWidth, y).lineWidth(1).strokeColor(BRAND).stroke();
      y += 8;
    },
    paragraph(text, { size = 9, color = MUTED_COLOR, font = 'Helvetica' } = {}) {
      doc.font(font).fontSize(size);
      const content = pdfText(text);
      const height = doc.heightOfString(content, { width: contentWidth });
      writer.ensure(height + 4);
      doc.fillColor(color).text(content, MARGIN, y, { width: contentWidth });
      y += height + 6;
    },
    /**
     * Table with a header row repeated on each page. columns = [{ label, width, align?, color?(row) }],
     * rows = arrays of cell texts.
     */
    table(columns, rows, { rowColors = null } = {}) {
      const drawHeader = () => {
        doc.rect(MARGIN, y, contentWidth, ROW_HEIGHT).fill(HEADER_FILL);
        doc.font('Helvetica-Bold').fontSize(9).fillColor(TEXT_COLOR);
        let x = MARGIN;
        columns.forEach((column) => {
          doc.text(fit(doc, column.label, column.width - 10), x + 5, y + 6, {
            width: column.width - 10,
            align: column.align || 'left',
            lineBreak: false,
          });
          x += column.width;
        });
        y += ROW_HEIGHT;
      };
      writer.ensure(ROW_HEIGHT * 2);
      drawHeader();
      rows.forEach((row, rowIndex) => {
        if (writer.ensure(ROW_HEIGHT)) drawHeader();
        let x = MARGIN;
        columns.forEach((column, index) => {
          const color = rowColors?.[rowIndex]?.[index] || TEXT_COLOR;
          doc.font(rowColors?.[rowIndex]?.[index] ? 'Helvetica-Bold' : 'Helvetica').fontSize(9).fillColor(color);
          doc.text(fit(doc, row[index], column.width - 10), x + 5, y + 6, {
            width: column.width - 10,
            align: column.align || 'left',
            lineBreak: false,
          });
          x += column.width;
        });
        y += ROW_HEIGHT;
        doc.moveTo(MARGIN, y).lineTo(MARGIN + contentWidth, y).lineWidth(0.5).strokeColor(BORDER_COLOR).stroke();
      });
      y += 6;
    },
  };
  return writer;
};

const drawHeader = (doc, texts, generatedOn) => {
  const width = doc.page.width;
  doc.rect(0, 0, width, 92).fill(BRAND);
  doc.font('Helvetica-Bold').fontSize(24).fillColor('#FFFFFF').text('CampusLink', MARGIN, 26, { lineBreak: false });
  doc.font('Helvetica').fontSize(11).fillColor('#FFFFFF').text(pdfText(texts.subtitle), MARGIN, 58, { lineBreak: false });
  doc
    .font('Helvetica')
    .fontSize(9)
    .fillColor('#FFFFFF')
    .text(pdfText(`${texts.generatedOn} ${generatedOn}`), MARGIN, 34, {
      width: width - MARGIN * 2,
      align: 'right',
      lineBreak: false,
    });
};

const drawIdentity = (doc, writer, rows) => {
  let y = 112;
  rows.forEach(([label, value]) => {
    doc.font('Helvetica-Bold').fontSize(10).fillColor(MUTED_COLOR).text(pdfText(label), MARGIN, y, { lineBreak: false });
    doc.font('Helvetica').fontSize(10).fillColor(TEXT_COLOR);
    doc.text(fit(doc, value, writer.contentWidth - 140), MARGIN + 140, y, { lineBreak: false });
    y += 16;
  });
  writer.y = y + 6;
};

const drawKpis = (doc, writer, kpis) => {
  const gap = 12;
  const boxWidth = (writer.contentWidth - gap * (kpis.length - 1)) / kpis.length;
  const height = 54;
  writer.ensure(height + 10);
  const y = writer.y;
  kpis.forEach(({ label, value, color }, index) => {
    const x = MARGIN + index * (boxWidth + gap);
    doc.roundedRect(x, y, boxWidth, height, 6).lineWidth(1).strokeColor(BORDER_COLOR).stroke();
    doc.font('Helvetica').fontSize(9).fillColor(MUTED_COLOR).text(fit(doc, label, boxWidth - 20), x + 10, y + 10, {
      lineBreak: false,
    });
    doc.font('Helvetica-Bold').fontSize(16).fillColor(color || BRAND).text(fit(doc, value, boxWidth - 20), x + 10, y + 26, {
      lineBreak: false,
    });
  });
  writer.y = y + height + 6;
};

const drawFooters = (doc, texts) => {
  const range = doc.bufferedPageRange();
  for (let index = range.start; index < range.start + range.count; index += 1) {
    doc.switchToPage(index);
    const y = doc.page.height - MARGIN - 14;
    const width = doc.page.width - MARGIN * 2;
    doc.moveTo(MARGIN, y - 6).lineTo(MARGIN + width, y - 6).lineWidth(0.5).strokeColor(BORDER_COLOR).stroke();
    doc.font('Helvetica').fontSize(8).fillColor(MUTED_COLOR);
    // The footer sits inside the bottom margin: keep pdfkit from adding a page.
    const bottomMargin = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    doc.text(pdfText(texts.footer), MARGIN, y, { lineBreak: false });
    doc.text(pdfText(texts.page(index - range.start + 1, range.count)), MARGIN, y, { width, align: 'right', lineBreak: false });
    doc.page.margins.bottom = bottomMargin;
  }
};

/**
 * Builds the PDF report of a student from analyticsService.studentAnalytics(...) data. Resolves to a Buffer.
 * @param {{ analytics: object, student: { firstname, lastname, email?, group? }, locale: 'fr'|'en', now?: Date }} input
 */
const buildStudentReport = ({ analytics, student, locale, now = new Date() }) =>
  new Promise((resolve, reject) => {
    const lang = locale === 'en' ? 'en' : 'fr';
    const texts = TEXTS[lang];
    const fullName = `${student.firstname ?? ''} ${student.lastname ?? ''}`.trim();
    const doc = new PDFDocument({
      size: 'A4',
      margins: { top: MARGIN, bottom: MARGIN, left: MARGIN, right: MARGIN },
      bufferPages: true,
      lang: lang === 'en' ? 'en-US' : 'fr-FR',
      info: {
        Title: pdfText(`${texts.documentTitle} - ${fullName}`),
        Author: 'CampusLink',
        Subject: pdfText(texts.subtitle),
        Creator: 'CampusLink',
        Producer: 'CampusLink',
      },
    });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    try {
      const writer = createWriter(doc);
      const limits = analytics.thresholds;
      drawHeader(doc, texts, formatDateTime(now, lang));

      const group = analytics.student?.group ?? null;
      const groupLabel = group
        ? [group.name, group.program ? `${group.program.name} (${group.program.code})` : null].filter(Boolean).join(' - ')
        : texts.noGroup;
      const identity = [[texts.student, fullName]];
      if (student.email) identity.push([texts.email, student.email]);
      identity.push([texts.group, groupLabel], [texts.academicYear, analytics.academicYear ?? '']);
      drawIdentity(doc, writer, identity);

      const attendance = analytics.attendance;
      const grades = analytics.grades;
      drawKpis(doc, writer, [
        {
          label: texts.kpiAbsence,
          value: formatPercent(attendance.overallRate, lang),
          color: LEVEL_COLORS[attendance.level] || BRAND,
        },
        { label: texts.kpiAverage, value: grades.overall === null ? '—' : `${formatAverage(grades.overall, lang)} / 20` },
        { label: texts.kpiAbsentHours, value: formatHours(attendance.absentHours, lang, texts) },
      ]);

      // Attendance
      writer.sectionTitle(texts.attendance);
      writer.paragraph(texts.attendanceNote(formatPercent(limits.warning, lang), formatPercent(limits.critical, lang)));
      if (attendance.bySubject.length === 0) {
        writer.paragraph(texts.noAttendance, { size: 10, color: TEXT_COLOR, font: 'Helvetica-Oblique' });
      } else {
        const rows = attendance.bySubject.map((entry) => [
          entry.subject?.name ?? '',
          formatHours(entry.heldHours, lang, texts),
          formatHours(entry.absentHours, lang, texts),
          formatPercent(entry.rate, lang),
          texts.levels[entry.level] ?? entry.level,
        ]);
        const colors = attendance.bySubject.map((entry) =>
          entry.level === 'OK' ? null : [null, null, null, LEVEL_COLORS[entry.level], LEVEL_COLORS[entry.level]]
        );
        writer.table(
          [
            { label: texts.subject, width: 160 },
            { label: texts.heldHours, width: 80, align: 'right' },
            { label: texts.absentHours, width: 92, align: 'right' },
            { label: texts.rate, width: 85, align: 'right' },
            { label: texts.level, width: writer.contentWidth - 417 },
          ],
          rows,
          { rowColors: colors }
        );
      }

      // Grades
      writer.sectionTitle(texts.grades);
      writer.paragraph(texts.gradesNote);
      const subjectsWithGrades = grades.bySubject;
      if (subjectsWithGrades.length === 0) {
        writer.paragraph(texts.noGrades, { size: 10, color: TEXT_COLOR, font: 'Helvetica-Oblique' });
      } else {
        writer.table(
          [
            { label: texts.subject, width: 255 },
            { label: texts.assessments, width: 110, align: 'right' },
            { label: texts.average, width: writer.contentWidth - 365, align: 'right' },
          ],
          subjectsWithGrades.map((entry) => [
            entry.subject?.name ?? '',
            String(entry.assessments),
            formatAverage(entry.average, lang),
          ])
        );
        const overallText = grades.overall === null ? '—' : `${formatAverage(grades.overall, lang)} / 20`;
        writer.paragraph(`${texts.overallAverage}${texts.colon}${overallText}`, {
          size: 11,
          color: BRAND,
          font: 'Helvetica-Bold',
        });

        const items = grades.items ?? [];
        if (items.length > 0) {
          writer.sectionTitle(texts.details);
          writer.table(
            [
              { label: texts.date, width: 75 },
              { label: texts.subject, width: 135 },
              { label: texts.assessment, width: 175 },
              { label: texts.coefficient, width: 40, align: 'right' },
              { label: texts.score, width: writer.contentWidth - 425, align: 'right' },
            ],
            items.map((item) => [
              formatDate(item.date, lang),
              item.subject?.name ?? '',
              item.title,
              formatNumber(item.coefficient, lang, { max: 2 }),
              item.score === null
                ? texts.notGraded
                : `${formatNumber(item.score, lang, { max: 2 })} / ${formatNumber(item.maxScore, lang, { max: 2 })}`,
            ])
          );
        }
      }

      drawFooters(doc, texts);
      doc.end();
    } catch (error) {
      reject(error);
      doc.end();
    }
  });

module.exports = { buildStudentReport, reportFilename, pdfText, TEXTS };
